package org.metahut.octopus.meta.starfish.bean;

/**
 *
 */
public enum RelType {
    /**
     * custom classes which are generated by janino
     */
    ENTITY,
    /**
     * classes which are in jdk or in jars
     */
    PRIMITIVE;
}
