messageQueue:
  type: pulsar
  pulsar:
    serviceUrl: pulsar://pulsar.com:6650
    adminUrl: http://pulsar.com:8080
    topic: persistent://data/quality/octopus.metrics.result
    subscriptionName: data.quality.dev
alertService: http://localhost:8989/alertSender/batchSendWithDetails
monitorFlowDefinitionService: http://localhost:8989/monitorFlowDefinition/
monitorRuleTask:
  type: flink
  jobName: data-quality-monitor


monitorStorage:
  type: clickhouse
  clickhouse:
    driverClassName: ru.yandex.clickhouse.ClickHouseDriver
    jdbcUrl: jdbc:clickhouse://localhost:8123/quality
    user: default
    password:

hiveConfitg:
  hiveConfDir: /opt/hive/conf
  version: 3.1.0